dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
  - $HOME/.m2
install: true
script:
   - mvn verify -B
   - system-test/start.sh
after_success:
  - mvn coveralls:report -B
